const movies = [
    {
    id: 1,
    title: "Captain America: Brave New World",
    imgUrl: "/image/america.jpeg",
    genre: "Action, Adventure",
    description: "Captain America faces new threats in a changing world.",
    releaseDate: "2024-07-26",
    duration: "150 min",
    actors: ["Anthony Mackie", "Harrison Ford", "Liv Tyler"],
    hasWatch: true,
    },
    {
    id: 2,
    title: "The Dark Knight",
    imgUrl: "/image/darknight.jpeg",
    genre: "Action, Crime, Drama",
    description: "Batman faces the Joker in a battle for Gotham.",
    releaseDate: "2008-07-18",
    duration: "152 min",
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    hasWatch: true,
    },
    {
    id: 3,
    title: "Deadpool & Wolverine",
    imgUrl: "/image/dead.jpeg",
    genre: "Action, Comedy",
    description: "Deadpool and Wolverine team up for an insane adventure.",
    releaseDate: "2024-11-08",
    duration: "140 min",
    actors: ["Ryan Reynolds", "Hugh Jackman"],
    hasWatch: true,
    },
    {
    id: 4,
    title: "Flow",
    imgUrl: "/image/flow.jpeg",
    genre: "Drama, Thriller",
    description: "A gripping thriller about unexpected twists.",
    releaseDate: "2025-03-15",
    duration: "120 min",
    actors: ["TBA"],
    hasWatch: true,
    },
    {
    id: 5,
    title: "Heart Eyes",
    imgUrl: "/image/hearteyes.jpeg",
    genre: "Romance, Drama",
    description: "A love story that will make your heart melt.",
    releaseDate: "2025-02-10",
    duration: "125 min",
    actors: ["TBA"],
    hasWatch: true,
    },
    {
    id: 6,
    title: "Iron Man 3",
    imgUrl: "/image/iron.jpeg",
    genre: "Action, Sci-Fi",
    description: "Tony Stark faces a powerful enemy, the Mandarin.",
    releaseDate: "2013-05-03",
    duration: "130 min",
    actors: ["Robert Downey Jr.", "Gwyneth Paltrow", "Ben Kingsley"],
    hasWatch: true,
    },
    {
    id: 7,
    title: "Kraven the Hunter",
    imgUrl: "/image/krav.jpeg",
    genre: "Action, Adventure",
    description: "Kraven, a legendary hunter, takes on his biggest challenge.",
    releaseDate: "2024-08-30",
    duration: "145 min",
    actors: ["Aaron Taylor-Johnson"],
    hasWatch: true,
    },
    {
    id: 8,
    title: "Mufasa: The Lion King",
    imgUrl: "/image/lion.jpeg",
    genre: "Animation, Adventure",
    description: "The untold story of Mufasa’s rise to power.",
    releaseDate: "2024-12-20",
    duration: "118 min",
    actors: ["TBA"],
    hasWatch: true,
    },
    {
    id: 9,
    title: "Moana 2",
    imgUrl: "/image/moana.jpeg",
    genre: "Animation, Adventure",
    description: "Moana embarks on another great journey.",
    releaseDate: "2024-11-27",
    duration: "115 min",
    actors: ["Auli’i Cravalho", "Dwayne Johnson"],
    hasWatch: true,
    },
    {
    id: 10,
    title: "The Monkey",
    imgUrl: "/image/monkey.jpeg",
    genre: "Horror, Thriller",
    description: "A terrifying tale of a cursed monkey.",
    releaseDate: "2025-04-05",
    duration: "122 min",
    actors: ["TBA"],
    hasWatch: true,
    },
    {
    id: 11,
    title: "Paddington in Peru",
    imgUrl: "/image/paddin.jpeg",
    genre: "Adventure, Comedy",
    description: "Paddington’s new adventure takes him to Peru.",
    releaseDate: "2024-11-08",
    duration: "110 min",
    actors: ["Ben Whishaw"],
    hasWatch: true,
    },
    {
    id: 12,
    title: "Red One",
    imgUrl: "/imager/redone.jpeg",
    genre: "Action, Comedy",
    description: "A holiday action-comedy adventure.",
    releaseDate: "2024-12-15",
    duration: "120 min",
    actors: ["Dwayne Johnson", "Chris Evans"],
    hasWatch: true,
    },
    {
    id: 13,
    title: "Sonic 3",
    imgUrl: "/image/sonic.jpeg",
    genre: "Animation, Action",
    description: "Sonic and friends return for another adventure.",
    releaseDate: "2024-12-20",
    duration: "110 min",
    actors: ["Ben Schwartz", "Idris Elba"],
    hasWatch: true,
    },
    {
    id: 14,
    title: "The Substance",
    imgUrl: "/image/substance.jpeg",
    genre: "Horror, Sci-Fi",
    description: "A mysterious substance changes lives.",
    releaseDate: "2025-01-10",
    duration: "118 min",
    actors: ["TBA"],
    hasWatch: true,
    },
    {
    id: 15,
    title: "Undercover Brother",
    imgUrl: "/image/undercover.jpeg",
    genre: "Comedy, Action",
    description: "A secret agent takes on a hilarious mission.",
    releaseDate: "2025-05-20",
    duration: "105 min",
    actors: ["TBA"],
    hasWatch: true,
    }
];